mutation AddRestaurant($name: String!, $location: String!, $price_range: Int!) {
        addRestaurant(name: $name, location: $location, price_range: $price_range) {
            id
            name
            location
            price_range
        }
    }